name: Update SSDF dotfiles
on:
  push:
    paths: [dotfiles/**]
jobs:
  update-dotfiles:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - nncore
    steps:
      - uses: actions/checkout@v2
        with:
          repository: itskyf/test-${{ matrix.repo }}
          path: test-${{ matrix.repo }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: ssdf-environment
      - run: cp -r ssdf-environment/dotfiles/. test-${{ matrix.repo }}
      - run: echo ${{ github.actor }} && echo ${{ github.event.pusher.email }}
      - uses: peter-evans/create-pull-request@v3
        with:
          committer: ${{ github.actor }} <${{ github.event.pusher.email }}>
          path: test-${{ matrix.repo }}
